### ISSUE TITLE
Why the long texts?

### ISSUE THREAD

**Issue by moritztim** [cirosantilli/cirosantilli.github.io#195]
I don't understand why your name is so long and many of your repo descriptions (which usually are expected to be short and concise) contain so much information, from install instructions to paragraphs of chinese text. It seems very cumbersome...

**Comment by moritztim** [comment]
I'm not trying to be mean by the way, I respect your work, it's very impressive and comprehensive, I'm just confused about this detail

**Comment by cirosantilli** [comment]
Hi. Because it makes me giggle.

**Comment by moritztim** [comment]
:pray: Thakn
