### ISSUE TITLE
Are you going to restore https://www.cirosantilli.com/git-tutorial/ ?

### ISSUE THREAD

**Issue by iBug** [cirosantilli/cirosantilli.github.io#41]
Hey Ciro, I'm a BIG fan of you!

I have quite a few links and references to you and your site on my site, and recently I spotted that one of them broke. It was <https://www.cirosantilli.com/git-tutorial/> (currently located on [this page](https://ibugone.com/skills) under the *Git* section).

Would you kindly guide me how I should handle that broken link? I'm always astounded whenever I see your tremendous page of Git tutorial, and I like it a lot.

**Comment by cirosantilli** [comment]
ibug! Thanks for reporting this. I had a little "force push accident yesterday". The pages in submodules have been restored.
