### ISSUE TITLE
sentence not very straight forward

### ISSUE THREAD

**Issue by jshen28** [cirosantilli/cirosantilli.github.io#74]
Hello,

I am reading x86-paging and thank you for excellent write-up. But I do have a question on a small [sentence](https://github.com/cirosantilli/cirosantilli.github.io/blob/b1ac03e62bd385cf9db648fbf0bfc901bb2d8a19/x86-paging.ciro#L52) and hope you can make more clear. Thank you

Best,

Norman

**Comment by cirosantilli** [comment]
Hi there,

> physical addresses can be though of the values that go to physical RAM index wires.

Memory can be thought of a box linked to the CPU box with input address wires, and data wires, have a look at this image: http://www.mathcs.emory.edu/~cheung/Courses/255/Syl-ARM/4-intro/bus-width.html

By "index wire" I meant data wires more precisely.

**Comment by jshen28** [comment]
ah, thank you for clarification.
