### ISSUE TITLE
Transcription+translation of Czech text from bitcoin-strings-with-txids

### ISSUE THREAD

**Issue by mormegil-cz** [cirosantilli/cirosantilli.github.io#81]
[The Czech hand-written text](https://github.com/cirosantilli/media/blob/master/bitcoin-strings-with-txids/data/bin/cc9c0b95ac772515235147d8354ec8b8b0763bf842ad16b8b23f855c3dc6a57e.jpg) reads:

> Svým podpisem pod tímto textem
> potvrzuji, že Daniela Dudysová a
> Pavel Urbaczka v mé přítomnosti
> dne 20.8.2016 v Ropici projevili vůli
> uzavřít spolu manželství, přičemž
> ani jeden z těchto projevů se mi
> nejevil jako nesvobodný, nikoliv
> vážný, nesrozumitelný, omylný nebo
> uzavřený v tísni.

Translation:
> With my signature under this text,
> I confirm Daniela Dudysová and
> Pavel Urbaczka have, in my presence
> on 2016-08-20 in Ropice, expressed
> the will to enter marriage, whereas
> neither of their expressions seemed to me
> to be non-free, not serious, in error, or
> under distress.

> [signatures: Tereza (unreadable) Hana (unreadable) Jakub (unreadable) Radim Kozub (unreadable) (unreadable) Lenka (unreadable)]

By looking at [Blockchain Legal team](https://www.blockchainlegal.cz/cs/tym), we might guess the Jakub to be Olšina.

**Comment by cirosantilli** [comment]
Thanks! Updated https://cirosantilli.com/cool-data-embedded-in-the-bitcoin-blockchain#image-hand-written-contract
