### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by topshenyi-web** [cirosantilli/cirosantilli.github.io#83]
How's life?

**Comment by cirosantilli** [comment]
Hi, I'm really sorry, I don't remember who you are, or don't recognize you from this account. Could you remind me here or through any other channel so I can reply more properly? Cheers!

**Comment by cirosantilli** [comment]
Ah, OK. I like those contacts.

Basically, I'm working full time on https://github.com/cirosantilli/ourbigbook/issues without users and without money. Will likely have to start some random job in a few months to get money.

What are you interests? What are you thinking for college? What do you think of High Technology High School? Do you get freedom to try real projects, or is it just grinding for stupid university exams? Doing/planning any cool projects? Happy to bounce some ideas.

I can also help with subjects if you need at some point. It's how I plan to bootstrap https://ourbigbook.com and good to help people.

**Comment by topshenyi-web** [comment]
Woah... I've never met someone online so interested to get to know me.  I think your project is pretty cool, (although do you think you'll succeed doing the whole thing alone?) and I also think that school is just a lot of meaningless work that won't turn out to be anything more than just a grade. I actually saw your name for the first time on a comment in a [Codeforces blog](https://codeforces.com/blog/entry/98165) that I posted a few months back, so stumbling upon a Github profile with the same name motivated me to take a look around. 
To illustrate how pointless these school assignments are, I'll provide a (very) recent example. There was a pygame group project due today, one that I had spent countless hours on for the past two months on, making the game as good as possible. (It was quite fun, but I had to carry most of it because my groupmates didn't really know how to code.) After the game presentation today, I came to the realization that after all the effort I put in, nothing meaningful was really going to come out of it, which made me pretty depressed. I mean, the repository's private so no one's going to see it, and it has basically no playable content because my group members were lazy and didn't put that much time into it, contrary to the amount of work I spent coding the game functionality. I'm thinking about improving it more and maybe adding it to my portfolio, but that's going to take some more time.

Just a little bit about me before my computer battery dies: I really like to code, and I spend much of my free time outside of school doing competitive programming or software dev projects. (but I don't have as much time/energy as I would like to put into these pursuits. I've been trying to wake up at 5am to get an upper hand on school, but it's made me a lot more tired.) 

(Hopefully my coding teacher doesn't see this :/)

**Comment by cirex-web** [comment]
would it be possible to make this issue private? I don't want other people to see this lol (It literally shows up on my profile homepage)

**Comment by cirosantilli** [comment]
I'll reply by email to erxu@ctemc.org Not possible to make individual issues private.
