### ISSUE TITLE
Some links to cirosantilli/ourbigbook repo doesn't work

### ISSUE THREAD

**Issue by kenorb** [cirosantilli/cirosantilli.github.io#88]
E.g.

- Page: https://cirosantilli.com/magic-the-gathering

Links at the footer which doesn't work:

- Website Git version: `dd39ce66c6738bab862eefc66b435a866f3f6388`
- Source code for this page: `magic-the-gathering.bigb`

**Comment by cirosantilli** [comment]
Yo, thanks for this Rafal. Good and old blind template copy pasting at work!

Glad to see your into mtg BTW.

**Comment by kenorb** [comment]
> Good and old blind template copy pasting at work!

Second one (_Website Git version_) still broken.

**Comment by kenorb** [comment]
> Glad to see your into mtg BTW.

It was more reading about what MTG is after reading article about cool hidden stuff in Bitcoin blockchain.

**Comment by cirosantilli** [comment]
I see. You're a crypto dude from your LinkedIn.
